services:
  backend:
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./logs:/app/logs
      - ./tests:/app/tests


    environment:

        APP_ENV: dev

    command:
      [
        "python",
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
    
    