"""baseline

Revision ID: 2a2e657c8c68
Revises:
Create Date: 2026-09-07 13:14:36.346497

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2a2e657c8c68"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
